; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Testability Driver Agent Qt
AppVerName=Testability Driver Agent Qt v0.9.2
AppPublisher=Nokia Oyj
AppPublisherURL=https://projects.forum.nokia.com/Testabilitydriver
AppSupportURL=https://projects.forum.nokia.com/Testabilitydriver
AppUpdatesURL=http://gitorious.org/tdriver/agent_qt
DefaultDirName=C:\qttas\bin
DisableDirPage=no
DefaultGroupName=Testability Driver Agent Qt
AllowNoIcons=yes
OutputBaseFilename=testability_driver_agent_qt_setup_0_9_2
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "basque"; MessagesFile: "compiler:Languages\Basque.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "danish"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "norwegian"; MessagesFile: "compiler:Languages\Norwegian.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "slovak"; MessagesFile: "compiler:Languages\Slovak.isl"
Name: "slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]

Source: "C:\qttas\bin\qttasserver.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\qttas\bin\qttas_ui.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Qt\2010.05\qt\plugins\tasfixtures\*"; DestDir: "C:\Qt\2010.05\qt\plugins\tasfixtures"; Flags: ignoreversion
Source: "C:\Qt\2010.05\qt\plugins\traversers\*"; DestDir: "C:\Qt\2010.05\qt\plugins\traversers"; Flags: ignoreversion
Source: "C:\Qt\2010.05\qt\plugins\testability\*"; DestDir: "C:\Qt\2010.05\qt\plugins\testability"; Flags: ignoreversion
Source: "C:\Qt\2010.05\qt\plugins\styles\*"; DestDir: "C:\Qt\2010.05\qt\plugins\styles"; Flags: ignoreversion



; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Qt TasServer Ui"; Filename: "{app}\qttas_ui.exe"; WorkingDir: "{app}"
Name: "{group}\{cm:UninstallProgram,Qt TasServer}"; Filename: "{uninstallexe}"
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Qt TasServer Ui"; Filename: "{app}\qttas_ui.exe"; Tasks: quicklaunchicon; WorkingDir: "{app}"

[Run]
Filename: "{app}\qttas_ui.exe"; Description: "Start Qt TasServer Ui"; Flags: postinstall shellexec skipifsilent


